---
title: "2b_withinEstimator"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Packages and data
```{r packages_and_data}
rm(list=ls())

library(tidyverse)
# library(lme4)
library(lmtest)

df_2011 <- read_csv("./Data/2b_WithinEstimator/LCP_2011_csv.csv")
df_2015 <- read_csv("./Data/2b_WithinEstimator/LCP_2015_csv.csv")
df_2017 <- read_csv("./Data/2b_WithinEstimator/LCP_2017_csv.csv")
```

### Combine years, group from/to core, m to km 
```{r packages_and_data}
df_full <- rbind(df_2011, df_2015, df_2017)

# Create to_from factor variable column
df_full$From_To <- as.factor(paste0(df_full$From_Core,"_",df_full$To_Core))
df_full$Year <- as.factor(df_full$Year)

# Convert meters to KM
df_full$CW_Dist_km <- df_full$CW_Dist/1000
df_full$LCP_Length_km <- df_full$LCP_Length/1000
df_full$Euc_Dist_km <- df_full$Euc_Dist/1000

```

### Within estimator regresssion
```{r within_reg}

ER_areg <- felm(Effective_Resistance ~ Year | From_To | 0 | From_To, data = df_full)
coeftest(ER_areg)

CWD_areg <- felm(CW_Dist_km ~ Year | From_To | 0 | From_To, data = df_full)
coeftest(CWD_areg)

CWDtoLCP_areg <- felm(cwd_to_Path_Length_Ratio ~ Year | From_To | 0 | From_To, data = df_full)
coeftest(CWDtoLCP_areg)

```


## New DFs for paired t-tests (Ashley reshapes data and keeps in one table instead)
```{r new_dfs}

df_2011 <- read_csv("./Data/2b_WithinEstimator/LCP_2011_csv.csv") %>% 
  select(Year,
         To_Core,
         From_Core,
         ER_2011=Effective_Resistance,
         CWD_2011=CW_Dist, 
         CWDtoLCP_2011=cwd_to_Path_Length_Ratio) %>% 
  mutate(From_To = as.factor(paste0(From_Core,"_",To_Core)),
         CWD_km_2011 = CWD_2011/1000)

df_2015 <- read_csv("./Data/2b_WithinEstimator/LCP_2015_csv.csv") %>% 
    select(Year,
         To_Core,
         From_Core,
         ER_2015=Effective_Resistance,
         CWD_2015=CW_Dist, 
         CWDtoLCP_2015=cwd_to_Path_Length_Ratio) %>% 
  mutate(From_To = as.factor(paste0(From_Core,"_",To_Core)),
         CWD_km_2015 = CWD_2015/1000)

df_2017 <- read_csv("./Data/2b_WithinEstimator/LCP_2017_csv.csv") %>% 
    select(Year,
         To_Core,
         From_Core,
         ER_2017=Effective_Resistance,
         CWD_2017=CW_Dist, 
         CWDtoLCP_2017=cwd_to_Path_Length_Ratio) %>% 
  mutate(From_To = as.factor(paste0(From_Core,"_",To_Core)),
         CWD_km_2017 = CWD_2017/1000)

df_full <- merge(df_2011,df_2015,by='From_To') %>% 
  merge(.,df_2017,by="From_To") %>% 
  select(1,5:8,12:15,19:22)

```


# Paired T.Tests
```{r paired_t_tests}

attach(df_full)
names(df_full)
# Effective Resistance vs 2011
t.test(ER_2011,ER_2015,paired = TRUE)
t.test(ER_2011,ER_2017,paired = TRUE)
t.test(ER_2015,ER_2017,paired = TRUE)

# CWD
t.test(CWD_km_2011,CWD_km_2015,paired = TRUE)
t.test(CWD_km_2011,CWD_km_2017,paired = TRUE)
t.test(CWD_km_2015,CWD_km_2017,paired = TRUE)

# LCP to CWD
t.test(CWDtoLCP_2011,CWDtoLCP_2015,paired = TRUE)
t.test(CWDtoLCP_2011,CWDtoLCP_2017,paired = TRUE)
t.test(CWDtoLCP_2015,CWDtoLCP_2017,paired = TRUE)
```



