---
title: "2b_withinEstimator"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Packages and data
```{r packages_and_data}
rm(list=ls())

library(tidyverse)
library(estimatr)
library(reshape2)

df_2011 <- read_csv("./Data/2b_WithinEstimator/LCP_2011_csv.csv")
df_2015 <- read_csv("./Data/2b_WithinEstimator/LCP_2015_csv.csv")
df_2017 <- read_csv("./Data/2b_WithinEstimator/LCP_2017_csv.csv")

df_reg <- rbind(df_2011, df_2015, df_2017)

# Create to_from factor variable column
df_reg$From_To <- as.factor(paste0(df_reg$From_Core,"_",df_reg$To_Core))
df_reg$Year <- as.factor(df_reg$Year)

# Convert meters to KM
df_reg$CW_Dist_km <- df_reg$CW_Dist/1000
df_reg$LCP_Length_km <- df_reg$LCP_Length/1000
df_reg$Euc_Dist_km <- df_reg$Euc_Dist/1000

```

### Within estimator regression
```{r withinReg}

###### LCP Length ######
# Reference year: 2011
lcp_length_km_lmrob <- estimatr::lm_robust(formula = LCP_Length_km ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(lcp_length_km_lmrob)

# Reference year: 2015
df_reg <- within(df_reg, Year <- relevel(Year, ref = '2015'))
lcp_length_km_lmrob15 <- lm_robust(formula = LCP_Length_km ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(lcp_length_km_lmrob15)

####### CWD Distance #######
# Reference year: 2011
df_reg <- within(df_reg, Year <- relevel(Year, ref = '2011'))
CWD_lmrob <- lm_robust(formula = CW_Dist_km ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(CWD_lmrob)

# Reference year: 2015
df_reg <- within(df_reg, Year <- relevel(Year, ref = '2015'))
CWD_lmrob15 <- lm_robust(formula = CW_Dist_km ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(CWD_lmrob15)

####### CWD to Path Length Distance #######
# Reference year: 2011
df_reg <- within(df_reg, Year <- relevel(Year, ref = '2011'))
CWDtoLCP_lmrob <- lm_robust(formula = cwd_to_Path_Length_Ratio ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(CWDtoLCP_lmrob)

# Reference year: 2015
df_reg <- within(df_reg, Year <- relevel(Year, ref = '2015'))
CWDtoLCP_lmrob15 <- lm_robust(formula = cwd_to_Path_Length_Ratio ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(CWDtoLCP_lmrob15)


###### Effective Resistance ######
# Reference year: 2011
df_reg <- within(df_reg, Year <- relevel(Year, ref = '2011'))
ER_lmrob <- lm_robust(formula = Effective_Resistance ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')

# Matching coefs and SEs, but no intercept
summary(ER_lmrob)

# Reference year: 2015
df_reg <- within(df_reg, Year <- relevel(Year, ref = '2015'))
ER_lmrob15 <- lm_robust(formula = Effective_Resistance ~ Year,
          data = df_reg,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(ER_lmrob15)

```


## New DFs for paired t-tests (Ashley reshapes data and keeps in one table instead)
```{r new_dfs}

df_2011 <- read_csv("./Data/2b_WithinEstimator/LCP_2011_csv.csv") %>%
  select(Year,
         To_Core,
         From_Core,
         ER_2011=Effective_Resistance,
         CWD_2011=CW_Dist,
         CWDtoLCP_2011=cwd_to_Path_Length_Ratio) %>%
  mutate(From_To = as.factor(paste0(From_Core,"_",To_Core)),
         CWD_km_2011 = CWD_2011/1000)

df_2015 <- read_csv("./Data/2b_WithinEstimator/LCP_2015_csv.csv") %>%
    select(Year,
         To_Core,
         From_Core,
         ER_2015=Effective_Resistance,
         CWD_2015=CW_Dist,
         CWDtoLCP_2015=cwd_to_Path_Length_Ratio) %>%
  mutate(From_To = as.factor(paste0(From_Core,"_",To_Core)),
         CWD_km_2015 = CWD_2015/1000)

df_2017 <- read_csv("./Data/2b_WithinEstimator/LCP_2017_csv.csv") %>%
    select(Year,
         To_Core,
         From_Core,
         ER_2017=Effective_Resistance,
         CWD_2017=CW_Dist,
         CWDtoLCP_2017=cwd_to_Path_Length_Ratio) %>%
  mutate(From_To = as.factor(paste0(From_Core,"_",To_Core)),
         CWD_km_2017 = CWD_2017/1000)

df_ttests <- merge(df_2011,df_2015,by='From_To') %>%
  merge(.,df_2017,by="From_To") %>%
  select(1,5:8,12:15,19:22)

```

# Paired T.Tests
```{r paired_t_tests}

attach(df_ttests)
# names(df_ttests)
# Effective Resistance vs 2011
t.test(ER_2011,ER_2015,paired = TRUE)
t.test(ER_2011,ER_2017,paired = TRUE)
t.test(ER_2015,ER_2017,paired = TRUE)

# CWD
t.test(CWD_km_2011,CWD_km_2015,paired = TRUE)
t.test(CWD_km_2011,CWD_km_2017,paired = TRUE)
t.test(CWD_km_2015,CWD_km_2017,paired = TRUE)

# LCP to CWD
t.test(CWDtoLCP_2011,CWDtoLCP_2015,paired = TRUE)
t.test(CWDtoLCP_2011,CWDtoLCP_2017,paired = TRUE)
t.test(CWDtoLCP_2015,CWDtoLCP_2017,paired = TRUE)
detach(df_ttests)
```

# Example results comparison: Within estimator regression versus T.tests on same sample with LCP to CWD ratio as outcome variable
```{r Ttest_reg_comparison}

# Subset regression dataset to only include paths that are also in the df_ttests set of From_To paths
df_reg_2 <- filter(df_reg,From_To %in% df_ttests$From_To)

# T.test
df_reg_2 <- within(df_reg_2, Year <- relevel(Year, ref = '2015'))
CWDtoLCP_lmrob <- lm_robust(formula = cwd_to_Path_Length_Ratio ~ Year,
          data = df_reg_2,
          clusters = From_To,
          fixed_effects = ~From_To,
          se_type = 'stata')
summary(CWDtoLCP_lmrob)

t.test(df_ttests$CWDtoLCP_2011,df_ttests$CWDtoLCP_2015,paired = TRUE)
t.test(df_ttests$CWDtoLCP_2011,df_ttests$CWDtoLCP_2017,paired = TRUE)
t.test(df_ttests$CWDtoLCP_2015,df_ttests$CWDtoLCP_2017,paired = TRUE)
```


